version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ffmpeg-static
    versions:
    - 4.2.7
    - 4.2.8
  - dependency-name: prism-media
    versions:
    - 1.2.3
    - 1.2.5
    - 1.2.6
    - 1.2.7
    - 1.2.8
  - dependency-name: node-telegram-bot-api
    versions:
    - 0.51.0
  - dependency-name: moment-timezone
    versions:
    - 0.5.32
  - dependency-name: node-gyp
    versions:
    - 7.1.2
  - dependency-name: lodash
    versions:
    - 4.17.20
